SITE_TITLE  = VG's blog
SITE_URL    = zlonet.ru
SITE_AUTHOR = Veniamin Gvozdikov
SITE_EMAIL  = vg@FreeBSD.org
AWK = awk
SITE_REPO_USER = zloidemon
SITE_REPO_PATH = ${SITE_REPO_USER}/${SITE_REPO_USER}.github.com
SITE_REPO_HTTP = https://github.com/${SITE_REPO_PATH}
SITE_REPO   = git@github.com:${SITE_REPO_PATH}.git
